#!/usr/bin/env python
import sys

from hardware_control.fan_control import set_fan_speed

if __name__ == "__main__":
    target = float(sys.argv[1])

    if target != 0 and (target < 0.1 or target > 1):
        print("Speed setting has to either 0 or between 0.1 and 1")
    else:
        print("Set fan speed to {0}%".format(str(target * 100)))
        set_fan_speed(target)

