#!/usr/bin/env python3
import sys

from hardware_control.peltier_control import set_hw_pwm_peltier_control

if __name__ == "__main__":
    target = float(sys.argv[1])

    if target < -1 or target > 1:
        print("Peltier power set-point has to be between -1 and 1")
    else:
        set_hw_pwm_peltier_control(target)
