#!/usr/bin/env python3

import os
import time

from hardware_control.temperature_sensors import room_temp_file, temp_file, read_temp
from utilities.formatters import timestamp

if __name__ == '__main__':
    os.system('modprobe w1-gpio')
    os.system('modprobe w1-therm')

    print("Time, Temp, Room temp")

    READS_FOLDER = '/brewmoth/temp-reads'

    file = open(os.path.join(READS_FOLDER, timestamp() + ".csv"), "w")

    try:
        while True:
            read = timestamp() + "," + str(read_temp(temp_file)) + "," + str(read_temp(room_temp_file))
            print(read)
            file.write(read)
            time.sleep(2)
    except KeyboardInterrupt:
        print("Exiting.")
    finally:
        file.close()
