#!/usr/bin/env python3
import argparse
import os
import time
from pathlib import Path

from hardware_control.temperature_sensors import room_temp_file, temp_file, read_temp
from utilities.constants import READS_FOLDER
from utilities.formatters import timestamp

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('--frequency', '-f', help='How often to read temps in seconds', default=5)

    args = parser.parse_args()
    frequency = float(args.frequency)

    os.system('modprobe w1-gpio')
    os.system('modprobe w1-therm')

    print("Time, Temp, Room temp")

    Path(READS_FOLDER).mkdir(parents=True, exist_ok=True)

    file = open(os.path.join(READS_FOLDER, timestamp() + ".csv"), "w")

    try:
        next_read = time.time()
        while True:
            current_time = time.time()

            if current_time > next_read:
                read = timestamp() + ", " + str(read_temp(temp_file)) + ", " + str(read_temp(room_temp_file))
                print(read)
                read += "\n"
                file.write(read)
                next_read = current_time + frequency

    except KeyboardInterrupt:
        print("Exiting.")
    finally:
        file.close()
